### ISSUE TITLE
Running error, missing libraries

### ISSUE THREAD

**Issue by Nabeelshar** [AbdulSami455/PSX-Data-Api-and-StockInfo-Wallet#1]
some libraries are not in requirement file, so its not running correctly even on docker compose.

**Comment by AbdulSami455** [comment]
can u give me the detail

**Comment by Nabeelshar** [comment]
To reproduce
Openup codespace on github so its fresh
install requirements.txt file
and run main.py
`
/home/codespace/.python/current/bin/python3 /workspaces/PSX-Data-Api/main.py
@Nabeelshar ➜ /workspaces/PSX-Data-Api (master) $ /home/codespace/.python/current/bin/python3 /workspaces/PSX-Data-Api/main.py
Traceback (most recent call last):
  File "/workspaces/PSX-Data-Api/main.py", line 5, in <module>
    from jose import JWTError, jwt
ModuleNotFoundError: No module named 'jose'
@Nabeelshar ➜ /workspaces/PSX-Data-Api (master) $ `

Even if you resolve this by install JWT there are still some libraries missing.

Create Codespace here
https://codespaces.new/AbdulSami455/PSX-Data-Api

**Comment by AbdulSami455** [comment]
please give me code and i will push it
