### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by njmulsqb** [AbdulSami455/PSX-Data-Api-and-StockInfo-Wallet#2]
Getting this error after installing all requirements
```
 ~/Dow/PSX-Data-Api | master ?1  python3 main.py
Traceback (most recent call last):
  File "/Users/administrator/Downloads/PSX-Data-Api/main.py", line 5, in <module>
    from jose import JWTError, jwt
  File "/Users/administrator/tools/BlobHunter/env/lib/python3.9/site-packages/jose.py", line 546
    print decrypt(deserialize_compact(jwt), {'k':key},
          ^
SyntaxError: invalid syntax
```

BTW, good project but need to be maintained.

**Comment by pddotabdur** [comment]
AOA, @njmulsqb @AbdulSami455 
Is this repo good for getting intra-day data for PSX based tickers. i need some work on intraday data not EOD data.

**Comment by AbdulSami455** [comment]
no , work is not done for intraday

**Comment by njmulsqb** [comment]
@AbdulSami455 why is the issue closed without proper reasoning of main issue
